### ISSUE TITLE
Does not install on Jessie

### ISSUE THREAD

**Issue by LeOSW42** [CotzaDev/rutorrent_ynh#1]
Hello,

I had some issues on jessie (Debian 8) :
- `deb-multimedia-keyring` is not available
- `ffmpeg` is not available
- One issue in rtorrent in ./configure :
  
  > ./configure: line 3019: syntax error near unexpected token `1.9.6'

Léo

**Comment by CotzaDev** [comment]
This should work now

**Comment by LeOSW42** [comment]
Ok, it seems better, everything install but rTorrent isn't launched :

> You are not the owner of /var/run/screen/S-rtorrent.

I cannot run this service

**Comment by LeOSW42** [comment]
Need to do that :

> chown rtorrent:rtorrent /var/run/screen/S-rtorrent
> chmod 700 /var/run/screen/S-rtorrent
> service rtorrent start
