### ISSUE TITLE
upgrade script does not upgrade rutorrent

### ISSUE THREAD

**Issue by stevenroose** [CotzaDev/rutorrent_ynh#2]
The ruTorrent files are kept as a git repo, so there has to be a git pull or something in the upgrade script to update ruTorrent.

**Comment by CotzaDev** [comment]
The sources are in the /tmp folder so they are deleted on reboot.
Now I check if the sources are still present in /tmp before trying to clone them.

**Comment by stevenroose** [comment]
I meant this repo
https://github.com/CotzaDev/rutorrent_ynh/blob/master/scripts/install#L71

**Comment by CotzaDev** [comment]
Ok, sorry.

I added a git pull to upgrade ruTorrent too.
